// This table contains the known Jumpmaze maps.
// ==========================================================================

interface Table {
   [ id: string ]: {
      lump: string,
      name: string,
      type: string,
      difficulty: string,
      // NOTE: The `goals` field only applies for 'team' maps, but we'll place
      // it in the general `map` table to keep things simple.
      goals: number,
      par: number,
   };
}

export default <Table> {

   // Jumpmaze
   // -----------------------------------------------------------------------
   
   map01: {
      lump: 'MAP01',
      name: 'Box Processing',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 33,
   },
   map02: {
      lump: 'MAP02',
      name: 'Downtown UAC',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 49,
   },
   map03: {
      lump: 'MAP03',
      name: 'Race to the Top!',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 39,
   },
   map04: {
      lump: 'MAP04',
      name: 'Mando\'s Express',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 70,
   },
   map05: {
      lump: 'MAP05',
      name: 'Storage Facility',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 83,
   },
   map06: {
      lump: 'MAP06',
      name: 'Nukage Lab',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 65,
   },
   map07: {
      lump: 'MAP07',
      name: 'The 30 Second Canyon',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 60,
   },
   map08: {
      lump: 'MAP08',
      name: 'Up the Frozen River',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 77,
   },
   map09: {
      lump: 'MAP09',
      name: 'Speed Arena',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 76,
   },
   map10: {
      lump: 'MAP10',
      name: 'Doomfiend\'s Blue Domain',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 122,
   },
   map11: {
      lump: 'MAP11',
      name: 'Canyon Complex',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 87,
   },
   map12: {
      lump: 'MAP12',
      name: 'Shadowed Fortress',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 76,
   },
   map13: {
      lump: 'MAP13',
      name: 'Tech Facility',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 102,
   },
   map14: {
      lump: 'MAP14',
      name: 'Factory Entrance',
      type: 'team',
      difficulty: 'moderate',
      goals: 4,
      par: 155,
   },
   map15: {
      lump: 'MAP15',
      name: 'Forest of the Undead',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 87,
   },
   map16: {
      lump: 'MAP16',
      name: 'Keo\'s Domain - Jumper\'s Path',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 130,
   },
   map17: {
      lump: 'MAP17',
      name: 'Hell\'s Fury',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 89,
   },
   map18: {
      lump: 'MAP18',
      name: 'Thumper\'s Perils of a Toxicity',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 175,
   },
   map19: {
      lump: 'MAP19',
      name: 'Skulltag Olympia 2008',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 132,
   },
   map20: {
      lump: 'MAP20',
      name: 'Canyons, Caves, and Lava. Oh my!',
      type: 'team',
      difficulty: 'hard',
      goals: 6,
      par: 173,
   },
   map21: {
      lump: 'MAP21',
      name: 'Castle Climb',
      type: 'team',
      difficulty: 'hard',
      goals: 5,
      par: 165,
   },
   map22: {
      lump: 'MAP22',
      name: 'Life of a Test Subject',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 142,
   },
   map23: {
      lump: 'MAP23',
      name: 'Escape From Lab 9',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 228,
   },
   map24: {
      lump: 'MAP24',
      name: 'Phendrana',
      type: 'team',
      difficulty: 'hard',
      goals: 4,
      par: 211,
   },
   map25: {
      lump: 'MAP25',
      name: 'Unholy Despair',
      type: 'team',
      difficulty: 'hard',
      goals: 5,
      par: 113,
   },
   map26: {
      lump: 'MAP26',
      name: 'Gosimers Jumpmaze',
      type: 'team',
      difficulty: 'veryhard',
      goals: 4,
      par: 222,
   },
   map27: {
      lump: 'MAP27',
      name: 'Welcome to the Void',
      type: 'team',
      difficulty: 'veryhard',
      goals: 8,
      par: 402,
   },
   map28: {
      lump: 'MAP28',
      name: 'Cloud 9',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 204,
   },
   map29: {
      lump: 'MAP29',
      name: 'Volcano Hallway',
      type: 'team',
      difficulty: 'veryhard',
      goals: 5,
      par: 168,
   },
   map30: {
      lump: 'MAP30',
      name: 'Fate of a Platformer',
      type: 'team',
      difficulty: 'veryhard',
      goals: 7,
      par: 272,
   },
   map31: {
      lump: 'MAP31',
      name: '4-Halls of Death',
      type: 'team',
      difficulty: 'veryhard',
      goals: 5,
      par: 408,
   },
   map32: {
      lump: 'MAP32',
      name: 'Precision Run',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 193,
   },

   // Jumpmaze 2
   // -----------------------------------------------------------------------

   map00: {
      lump: 'MAP00',
      name: 'Training',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   map33: {
      lump: 'MAP33',
      name: 'Jump Trials',
      type: 'solo',
      difficulty: 'varied',
      goals: 0,
      par: 330,
   },
   map34: {
      lump: 'MAP34',
      name: 'Junglefalls',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 160,
   },
   map35: {
      lump: 'MAP35',
      name: 'Rage Maze',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 75,
   },
   map36: {
      lump: 'MAP36',
      name: 'Goldfinger',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 110,
   },
   map37: {
      lump: 'MAP37',
      name: 'Volcano Escape',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 146,
   },
   map38: {
      lump: 'MAP38',
      name: 'Jumpmaze Circuit',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 130,
   },
   map39: {
      lump: 'MAP39',
      name: 'Escape from Hell',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 160,
   },
   map40: {
      lump: 'MAP40',
      name: 'Proteh\'s Chaos Base',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 120,
   },
   map41: {
      lump: 'MAP41',
      name: 'Jump City',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 105,
   },
   map42: {
      lump: 'MAP42',
      name: 'Lost Halls',
      type: 'team',
      difficulty: 'moderate',
      goals: 4,
      par: 147,
   },
   map43: {
      lump: 'MAP43',
      name: 'Lava Laboratory',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   map44: {
      lump: 'MAP44',
      name: 'Jumpmaze-HQ',
      type: 'team',
      difficulty: 'hard',
      goals: 5,
      par: 119,
   },
   map45: {
      lump: 'MAP45',
      name: 'Durch Die Holle Gehen',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 350,
   },
   map46: {
      lump: 'MAP46',
      name: 'Blocks of Doom',
      type: 'team',
      difficulty: 'moderate',
      goals: 6,
      par: 269,
   },
   map47: {
      lump: 'MAP47',
      name: 'Druglab',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 150,
   },
   map48: {
      lump: 'MAP48',
      name: 'Escaping from the Horror',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 198,
   },
   map49: {
      lump: 'MAP49',
      name: 'Kill Ratio',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 120,
   },
   map50: {
      lump: 'MAP50',
      name: 'Space-Station',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 140,
   },
   map51: {
      lump: 'MAP51',
      name: 'Port Town',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 172,
   },
   map52: {
      lump: 'MAP52',
      name: 'Vivid Dreams, Sweetheart',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 168,
   },
   map53: {
      lump: 'MAP53',
      name: 'Doomed Cruise',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 150,
   },
   map54: {
      lump: 'MAP54',
      name: 'Jumping Factory',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 107,
   },
   map55: {
      lump: 'MAP55',
      name: 'Bloody Donation',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 283,
   },
   map56: {
      lump: 'MAP56',
      name: 'Red Hot Ride',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 168,
   },
   map57: {
      lump: 'MAP57',
      name: 'Core Dump',
      type: 'team',
      difficulty: 'veryhard',
      goals: 7,
      par: 423,
   },
   map58: {
      lump: 'MAP58',
      name: 'Red Hot Ride II',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 155,
   },
   map59: {
      lump: 'MAP59',
      name: 'Rage Maze 2',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 135,
   },
   map60: {
      lump: 'MAP60',
      name: '40 Below Zero',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 239,
   },
   map61: {
      lump: 'MAP61',
      name: 'Sweet Dreams Wario',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 166,
   },
   map62: {
      lump: 'MAP62',
      name: 'AAC\'s Hive',
      type: 'team',
      difficulty: 'easy',
      goals: 5,
      par: 90,
   },
   map63: {
      lump: 'MAP63',
      name: 'Across the Dark Swamp',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 598,
   },
   map64: {
      lump: 'MAP64',
      name: 'The Last Hurrah',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 198,
   },
   rject01: {
      lump: 'RJECT01',
      name: 'Infer\'s Hell',
      type: 'team',
      difficulty: 'moderate',
      goals: 0,
      par: 210,
   },
   rject02: {
      lump: 'RJECT02',
      name: 'Eternal Void',
      type: 'team',
      difficulty: 'veryhard',
      goals: 6,
      par: 275,
   },
   rject03: {
      lump: 'RJECT03',
      name: 'Gravity Chambers',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 283,
   },
   rject04: {
      lump: 'RJECT04',
      name: 'Airship Doomed',
      type: 'team',
      difficulty: 'hard',
      goals: 8,
      par: 352,
   },
   rject05: {
      lump: 'RJECT05',
      name: 'Islands of Desolation',
      type: 'team',
      difficulty: 'hard',
      goals: 3,
      par: 164,
   },
   rject06: {
      lump: 'RJECT06',
      name: 'Interrogator',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 110,
   },
   rject07: {
      lump: 'RJECT07',
      name: 'Gravity Station',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 146,
   },
   drag: {
      lump: 'DRAG',
      name: 'Drag Race',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 18,
   },
   floorlav: {
      lump: 'FLOORLAV',
      name: 'Floor is Lava',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 40,
   },
   grav: {
      lump: 'GRAV',
      name: 'Gravity Chambers Redux',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 120,
   },
   shit: {
      lump: 'SHIT',
      name: 'The Key to Victory',
      type: 'solo',
      difficulty: 'none',
      goals: 0,
      par: 0, // No par.
   },

   // Jumpix
   // -----------------------------------------------------------------------

   jpx01: {
      lump: 'JPX01',
      name: 'Badlands',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 35,
   },
   jpx02: {
      lump: 'JPX02',
      name: 'Raiden',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 20,
   },
   jpx03: {
      lump: 'JPX03',
      name: 'Occupied Waters',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 47,
   },
   jpx04: {
      lump: 'JPX04',
      name: 'Chem VI',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 80,
   },
   jpx05: {
      lump: 'JPX05',
      name: 'Haunted Hall',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 52,
   },
   jpx06: {
      lump: 'JPX06',
      name: 'Mountain Jump',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 60,
   },
   jpx07: {
      lump: 'JPX07',
      name: 'Across The Canyon and Into the Caves',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 120,
   },
   jpx08: {
      lump: 'JPX08',
      name: 'Nukage',
      type: 'team',
      difficulty: 'easy',
      goals: 3,
      par: 150,
   },
   jpx09: {
      lump: 'JPX09',
      name: 'Space Race',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 120,
   },
   jpx10: {
      lump: 'JPX10',
      name: 'The Mill',
      type: 'team',
      difficulty: 'easy',
      goals: 5,
      par: 120,
   },
   jpx11: {
      lump: 'JPX11',
      name: 'Darkest Chasm',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 100,
   },
   jpx12: {
      lump: 'JPX12',
      name: 'Tunnel Trouble',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 120,
   },
   jpx13: {
      lump: 'JPX13',
      name: 'Crusaders Corridor',
      type: 'team',
      difficulty: 'moderate',
      goals: 5,
      par: 180,
   },
   jpx14: {
      lump: 'JPX14',
      name: 'Hot-Head Bop',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 90,
   },
   jpx15: {
      lump: 'JPX15',
      name: 'Jumpenstein',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 70,
   },
   jpx16: {
      lump: 'JPX16',
      name: 'Fire Field',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 110,
   },
   jpx17: {
      lump: 'JPX17',
      name: 'Ruins',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 152,
   },
   jpx18: {
      lump: 'JPX18',
      name: 'The Sixth Dimension',
      type: 'team',
      difficulty: 'moderate',
      goals: 7,
      par: 180,
   },
   jpx19: {
      lump: 'JPX19',
      name: 'Path of Peril',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 205,
   },
   jpx20: {
      lump: 'JPX20',
      name: 'Computer Lab',
      type: 'team',
      difficulty: 'hard',
      goals: 6,
      par: 176,
   },
   jpx21: {
      lump: 'JPX21',
      name: 'Entering Hell',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 177,
   },
   jpx22: {
      lump: 'JPX22',
      name: 'Veins',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 165,
   },
   jpx23: {
      lump: 'JPX23',
      name: 'Cave',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 226,
   },
   jpx24: {
      lump: 'JPX24',
      name: 'Castle',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 355,
   },
   jpx25: {
      lump: 'JPX25',
      name: '[EDK] Fortress',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 220,
   },
   jpx26: {
      lump: 'JPX26',
      name: 'Pain and Agony',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 165,
   },
   jpx27: {
      lump: 'JPX27',
      name: 'The Nightmare',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 345,
   },
   jpx28: {
      lump: 'JPX28',
      name: 'Depths of Darkness',
      type: 'team',
      difficulty: 'veryhard',
      goals: 3,
      par: 225,
   },
   jpx29: {
      lump: 'JPX29',
      name: 'New Mojave',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 98,
   },
   jpx30: {
      lump: 'JPX30',
      name: 'Itaipu',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 600,
   },
   jpx31: {
      lump: 'JPX31',
      name: 'A Winter Dream',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 150,
   },
   jpx32: {
      lump: 'JPX32',
      name: 'First Strike',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 229,
   },
   jpxsec: {
      lump: 'JPXSEC',
      name: 'Happy Dreams',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 105,
   },
   jpxsec2: {
      lump: 'JPXSEC2',
      name: 'Colors',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 60,
   },
   jpxsec3: {
      lump: 'JPXSEC3',
      name: 'Tribal Unity',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 30,
   },
   bass: {
      lump: 'BASS',
      name: 'Bass',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 30,
   },

   // Jumpix 2
   // -----------------------------------------------------------------------

   jpx33: {
      lump: 'JPX33',
      name: 'Lago Ypacarai',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 73,
   },
   jpx34: {
      lump: 'JPX34',
      name: 'ELTSAC SSG',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 37,
   },
   jpx35: {
      lump: 'JPX35',
      name: 'Iron Bricks',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 101,
   },
   jpx36: {
      lump: 'JPX36',
      name: 'Elemental',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 148,
   },
   jpx37: {
      lump: 'JPX37',
      name: 'Mother Nature\'s Home',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 159,
   },
   jpx38: {
      lump: 'JPX38',
      name: 'Eternal',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 192,
   },
   jpx39: {
      lump: 'JPX39',
      name: 'The Strongest Spirit',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 240,
   },
   jpx40: {
      lump: 'JPX40',
      name: 'Cave',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 54,
   },
   jpx41: {
      lump: 'JPX41',
      name: 'The Laboratory',
      type: 'team',
      difficulty: 'moderate',
      goals: 5,
      par: 75,
   },
   jpx42: {
      lump: 'JPX42',
      name: 'Mansion',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 166,
   },
   jpx49: {
      lump: 'JPX49',
      name: 'Industrial Machinery',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 83,
   },
   jpx50: {
      lump: 'JPX50',
      name: 'ZteelWorx',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 167,
   },
   jpx51: {
      lump: 'JPX51',
      name: 'Planet Odd',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 154,
   },
   jpx52: {
      lump: 'JPX52',
      name: 'Twinkle Snow',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 182,
   },
   jpx53: {
      lump: 'JPX53',
      name: 'Dammit',
      type: 'team',
      difficulty: 'veryhard',
      goals: 6,
      par: 436,
   },
   jpx54: {
      lump: 'JPX54',
      name: 'Siege of He Fei Castle',
      type: 'team',
      difficulty: 'hard',
      goals: 6,
      par: 143,
   },
   jpx55: {
      lump: 'JPX55',
      name: 'UAC Base',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 95,
   },
   jpx56: {
      lump: 'JPX56',
      name: 'Buildings and Pipes',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 160,
   },
   jpxiisec: {
      lump: 'JPXIISEC',
      name: 'Feudal Age',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 120,
   },
   jpx2bdem: {
      lump: 'JPX2BDEM',
      name: 'Library',
      type: 'solo',
      difficulty: 'varied',
      goals: 0,
      par: 0,
   },

   // Lightmaze
   // -----------------------------------------------------------------------

   green: {
      lump: 'GREEN',
      name: 'Green Jumpmaze',
      type: 'team',
      difficulty: 'moderate',
      goals: 3,
      par: 60,
   },
   ljm01: {
      lump: 'LJM01',
      name: 'Poison',
      type: 'solo',
      difficulty: 'moderate',
      goals: 4,
      par: 71,
   },
   ljm02: {
      lump: 'LJM02',
      name: 'Cross The Islands',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 14,
   },
   ljm03: {
      lump: 'LJM03',
      name: 'Gotcha!',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 33,
   },
   ljm04: {
      lump: 'LJM04',
      name: 'The Canyon',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 60,
   },
   ljm05: {
      lump: 'LJM05',
      name: 'Interplanetary Jumpmaze',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 50,
   },
   ljm06: {
      lump: 'LJM06',
      name: 'Winter',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 107,
   },
   ljm07: {
      lump: 'LJM07',
      name: 'The Lava Void',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 54,
   },
   ljm08: {
      lump: 'LJM08',
      name: 'Plane of Fire',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 183,
   },
   ljm09: {
      lump: 'LJM09',
      name: 'Land Of Misery',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 45,
   },
   ljm10: {
      lump: 'LJM10',
      name: 'Mount Sewer',
      type: 'team',
      difficulty: 'easy',
      goals: 4,
      par: 73,
   },
   ljm11: {
      lump: 'LJM11',
      name: 'Cross The Islands II',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 30,
   },
   ljm12: {
      lump: 'LJM12',
      name: 'Big River',
      type: 'team',
      difficulty: 'hard',
      goals: 3,
      par: 127,
   },
   ljm13: {
      lump: 'LJM13',
      name: 'Cliffside Pass',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 137,
   },
   ljm14: {
      lump: 'LJM14',
      name: 'Hotlands',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 169,
   },
   ljm15: {
      lump: 'LJM15',
      name: 'Hoots Of A Platformer',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 177,
   },
   ljm16: {
      lump: 'LJM16',
      name: 'Undergrounds',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 70,
   },

   // Neojump
   // -----------------------------------------------------------------------

   neo01: {
      lump: 'NEO01',
      name: '3, 2, 1, JUMP!',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 30,
   },
   neo02: {
      lump: 'NEO02',
      name: 'Through the Sewer',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 80,
   },
   neo03: {
      lump: 'NEO03',
      name: 'The Highway',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 50,
   },
   neo04: {
      lump: 'NEO04',
      name: 'Storage Facility',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   neo05: {
      lump: 'NEO05',
      name: 'Temple of Darkness',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   neo06: {
      lump: 'NEO06',
      name: 'The Mechanical Tower',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   neo07: {
      lump: 'NEO07',
      name: 'Incoming Flood',
      type: 'team',
      difficulty: 'easy',
      goals: 5,
      par: 150,
   },
   neo08: {
      lump: 'NEO08',
      name: 'Something to Remember',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 150,
   },
   neo09: {
      lump: 'NEO09',
      name: 'The Core',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 150,
   },
   neo10: {
      lump: 'NEO10',
      name: 'UAC Complex',
      type: 'team',
      difficulty: 'easy',
      goals: 5,
      par: 165,
   },
   neo11: {
      lump: 'NEO11',
      name: 'Lava Castle',
      type: 'team',
      difficulty: 'moderate',
      goals: 3,
      par: 115,
   },
   neo12: {
      lump: 'NEO12',
      name: 'Tetris World',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 165,
   },
   neo13: {
      lump: 'NEO13',
      name: 'Valley Island',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 90,
   },
   neo14: {
      lump: 'NEO14',
      name: 'Madness',
      type: 'team',
      difficulty: 'hard',
      goals: 6,
      par: 240,
   },

   // Hypnojump
   // -----------------------------------------------------------------------

   hyp01: {
      lump: 'HYP01',
      name: 'Offshore Industrial Park',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 95,
   },
   hyp02: {
      lump: 'HYP02',
      name: 'Doom 2 Jumpmaze',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 150,
   },
   hyp03: {
      lump: 'HYP03',
      name: 'Snowccelerate!',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 60,
   },
   hyp04: {
      lump: 'HYP04',
      name: 'Race around the Production Line',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 23,
   },
   hyp05: {
      lump: 'HYP05',
      name: 'Adventures in Bongland',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 90,
   },
   hyp06: {
      lump: 'HYP06',
      name: 'Hypnotoad\'s Castle of Champions',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 140,
   },

   // Retromaze
   // -----------------------------------------------------------------------

   rjm01: {
      lump: 'RJM01',
      name: 'Back to the Basics',
      type: 'team',
      difficulty: 'varied',
      goals: 8,
      par: 600,
   },
   rjm02: {
      lump: 'RJM02',
      name: 'Blast to the Past',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 90,
   },
   rjm03: {
      lump: 'RJM03',
      name: 'The Eagle',
      type: 'team',
      difficulty: 'veryhard',
      goals: 3,
      par: 150,
   },
   rjm04: {
      lump: 'RJM04',
      name: 'Sendo Reaper\'s Resting Place',
      type: 'team',
      difficulty: 'veryhard',
      goals: 4,
      par: 300,
   },
   rjmold01: {
      lump: 'RJMOLD01',
      name: 'Blaster Master Platformer',
      type: 'team',
      difficulty: 'varied',
      goals: 5,
      par: 600,
   },

   // Neojump X
   // -----------------------------------------------------------------------

   xneo02: {
      lump: 'XNEO02',
      name: 'Waste Processing Plant',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 60,
   },
   xneo03: {
      lump: 'XNEO03',
      name: 'Pillars of Success',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 150,
   },
   xneo06: {
      lump: 'XNEO06',
      name: 'Water Processing Plant',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 90,
   },
   xneo11: {
      lump: 'XNEO11',
      name: 'Lava Castle',
      type: 'team',
      difficulty: 'hard',
      goals: 9,
      par: 180,
   },
   xneo13: {
      lump: 'XNEO13',
      name: 'Valley Island',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 120,
   },

   // NotCXJump
   // -----------------------------------------------------------------------

   ncj01: {
      lump: 'NCJ01',
      name: 'Ghosts',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 75,
   },
   ncj02: {
      lump: 'NCJ02',
      name: 'Vector',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 30,
   },
   ncj03: {
      lump: 'NCJ03',
      name: 'The Octagon',
      type: 'team',
      difficulty: 'moderate',
      goals: 7,
      par: 180,
   },
   ncj04: {
      lump: 'NCJ04',
      name: 'The Cave',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 150,
   },
   ncj05: {
      lump: 'NCJ05',
      name: '(Not)CXJump Circuit',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 25,
   },
   ncjsec: {
      lump: 'NCJSEC',
      name: 'The Hoppening',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 12,
   },

   // AAC
   // -----------------------------------------------------------------------

   aac01: {
      lump: 'AAC01',
      name: 'Unknown Lab',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 55,
   },
   aac02: {
      lump: 'AAC02',
      name: 'Around the world',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 125,
   },
   aac03: {
      lump: 'AAC03',
      name: 'Turbo Tunnel',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 110,
   },
   aac04: {
      lump: 'AAC04',
      name: 'Travincal',
      type: 'team',
      difficulty: 'veryhard',
      goals: 9,
      par: 273,
   },
   aac05: {
      lump: 'AAC05',
      name: 'New Territories',
      type: 'team',
      difficulty: 'veryhard',
      goals: 6,
      par: 220,
   },
   aac06: {
      lump: 'AAC06',
      name: 'Central de Procesamiento',
      type: 'team',
      difficulty: 'hard',
      goals: 8,
      par: 270,
   },
   aac07: {
      lump: 'AAC07',
      name: 'Purgatory',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 150,
   },

   // Advanced Jumpmaze
   // -----------------------------------------------------------------------

   adv01: {
      lump: 'ADV01',
      name: 'Pressure Point',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 200,
   },
   adv02: {
      lump: 'ADV02',
      name: 'Hades Vendetta',
      type: 'solo',
      difficulty: 'veryveryhard',
      goals: 0,
      par: 245,
   },
   adv03: {
      lump: 'ADV03',
      name: 'Momentum',
      type: 'solo',
      difficulty: 'veryveryhard',
      goals: 0,
      par: 300,
   },
   adv04: {
      lump: 'ADV04',
      name: 'Tough Day',
      type: 'solo',
      difficulty: 'extreme2',
      goals: 0,
      par: 360,
   },
   adv05: {
      lump: 'ADV05',
      name: 'Castle, Skins and Hell!',
      type: 'solo',
      difficulty: 'extreme',
      goals: 0,
      par: 360,
   },
   adv06: {
      lump: 'ADV06',
      name: 'Magnetic Flux',
      type: 'team',
      difficulty: 'fuckyoudevon',
      goals: 7,
      par: 1417,
   },
   adv07: {
      lump: 'ADV07',
      name: 'Limites',
      type: 'solo',
      difficulty: 'cruel',
      goals: 0,
      par: 420,
   },
   adv08: {
      lump: 'ADV08',
      name: 'Inner Peace',
      type: 'team',
      difficulty: 'veryveryhard',
      goals: 5,
      par: 300,
   },
   adv09: {
      lump: 'ADV09',
      name: 'Malignance',
      type: 'solo',
      difficulty: 'extreme3',
      goals: 0,
      par: 600,
   },
   fllv2: {
      lump: 'FLLV2',
      name: 'Industrial Rage',
      type: 'solo',
      difficulty: 'killyourself',
      goals: 0,
      par: 30,
   },

   // Jumpmaze X
   // -----------------------------------------------------------------------

   jmx00a: {
      lump: 'JMX00A',
      name: 'Floor 1: Denial',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 54,
   },
   jmx00b: {
      lump: 'JMX00B',
      name: 'Floor 2: Anger',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 78,
   },
   jmx00c: {
      lump: 'JMX00C',
      name: 'Floor 3: Bargaining',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 97,
   },
   jmx00d: {
      lump: 'JMX00D',
      name: 'Floor 4: Depression',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 120,
   },
   jmx00e: {
      lump: 'JMX00E',
      name: 'Floor 5: Acceptance',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 130,
   },
   jmx00f: {
      lump: 'JMX00F',
      name: 'True Fate of a Platformer',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 43,
   },
   jmx01: {
      lump: 'JMX01',
      name: 'Isolation',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 41,
   },
   jmx02: {
      lump: 'JMX02',
      name: 'Night Life at the Pier',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 46,
   },
   jmx03: {
      lump: 'JMX03',
      name: 'Nice Jumpin\' Pardner',
      type: 'solo',
      difficulty: 'veryeasy',
      goals: 0,
      par: 39,
   },
   jmx04: {
      lump: 'JMX04',
      name: 'Welcome to the UAC, Kid',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 81,
   },
   jmx05: {
      lump: 'JMX05',
      name: 'Magical Falls',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 86,
   },
   jmx06: {
      lump: 'JMX06',
      name: 'Aquatic Expedition',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 119,
   },
   jmx07: {
      lump: 'JMX07',
      name: 'Journey to the Center of the Earth',
      type: 'solo',
      difficulty: 'easy',
      goals: 0,
      par: 122,
   },
   jmx08: {
      lump: 'JMX08',
      name: 'Ruins of the Castle in the Sky',
      type: 'team',
      difficulty: 'easy',
      goals: 7,
      par: 166,
   },
   jmx09: {
      lump: 'JMX09',
      name: 'Abandonando Habitos',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 148,
   },
   jmx10: {
      lump: 'JMX10',
      name: 'The Lost Village',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 170,
   },
   jmx11: {
      lump: 'JMX11',
      name: 'A Cavernous Adventure',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 211,
   },
   jmx12: {
      lump: 'JMX12',
      name: 'Rockface Rumble',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 165,
   },
   jmx13: {
      lump: 'JMX13',
      name: 'Aurora Australis',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 175,
   },
   jmx14: {
      lump: 'JMX14',
      name: 'Gear Tower Grind',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 171,
   },
   jmx15: {
      lump: 'JMX15',
      name: 'Spooky Scary -Redacted-',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 217,
   },
   jmx16: {
      lump: 'JMX16',
      name: 'Reach for the Moon, Mortal Doomguy',
      type: 'team',
      difficulty: 'moderate',
      goals: 4,
      par: 212,
   },
   jmx17: {
      lump: 'JMX17',
      name: 'The Ancient Demon\'s Paradise',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 201,
   },
   jmx18: {
      lump: 'JMX18',
      name: 'Legend of Mt. Fuji',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 243,
   },
   jmx19: {
      lump: 'JMX19',
      name: 'Traptrix Temple',
      type: 'team',
      difficulty: 'hard',
      goals: 5,
      par: 298,
   },
   jmx20: {
      lump: 'JMX20',
      name: 'Technomania',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 325,
   },
   jmx21: {
      lump: 'JMX21',
      name: 'Relics of the Past',
      type: 'team',
      difficulty: 'hard',
      goals: 5,
      par: 287,
   },
   jmx22: {
      lump: 'JMX22',
      name: 'End of the Line',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 334,
   },
   jmx23: {
      lump: 'JMX23',
      name: 'Secrets of the Red Planet',
      type: 'solo',
      difficulty: 'hard',
      goals: 0,
      par: 468,
   },
   jmx24: {
      lump: 'JMX24',
      name: 'Monze',
      type: 'team',
      difficulty: 'hard',
      goals: 11,
      par: 411,
   },
   jmx25: {
      lump: 'JMX25',
      name: 'Castle Chaos',
      type: 'team',
      difficulty: 'veryhard',
      goals: 10,
      par: 643,
   },
   jmx26: {
      lump: 'JMX26',
      name: 'Mechanical Haunting',
      type: 'team',
      difficulty: 'veryhard',
      goals: 7,
      par: 712,
   },
   jmx27: {
      lump: 'JMX27',
      name: 'Frozen Sanctuary',
      type: 'team',
      difficulty: 'veryhard',
      goals: 11,
      par: 817,
   },
   jmx28: {
      lump: 'JMX28',
      name: 'Road to Revival',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 496,
   },
   jmx29: {
      lump: 'JMX29',
      name: 'The Tower of Babel',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 600,
   },
   jmx30: {
      lump: 'JMX30',
      name: 'Determination',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 301,
   },
   jmx31: {
      lump: 'JMX31',
      name: 'Zandro Olympia 20XX',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 298,
   },
   jmx32: {
      lump: 'JMX32',
      name: 'Journey\'s End',
      type: 'team',
      difficulty: 'veryhard',
      goals: 12,
      par: 572,
   },
   jmx33: {
      lump: 'JMX33',
      name: 'Epilogue',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 83,
   },

   // Standalone maps
   // -----------------------------------------------------------------------

   trash01: {
      lump: 'TRASH01',
      name: 'Nuclear Toxin',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 30,
   },
   trash02: {
      lump: 'TRASH02',
      name: 'In the Skies',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 30,
   },
   gmz02: {
      lump: 'GMZ02',
      name: 'New York City',
      type: 'solo',
      difficulty: 'veryhard',
      goals: 0,
      par: 215,
   },
   zteel: {
      lump: 'ZTEEL',
      name: 'ZteelWorx 2',
      type: 'solo',
      difficulty: 'moderate',
      goals: 0,
      par: 133,
   },
};